### ISSUE TITLE
运行frontend模块报错

### ISSUE THREAD

**Issue by 80sAzhong** [nebula-chat/chatengine#12]
我按照文档编译和运行顺序操作时，在最后运行frontend模块时提示端口占用：{0xc0000f71e0 /nebulaim/frontend80/node1 {"Addr":"127.0.0.1:10000","Metadata":{}} 10000000000 0xc00009d500 0x593570}
F0529 21:03:22.584240   18720 mtproto_server.go:66] Endpoint already exists for id: client-bufv8c5dtrq8，查看源代码文件中如下：
![image](https://user-images.githubusercontent.com/21975431/58559438-b7dc2600-8255-11e9-9cc4-5d8eec5ae1ef.png)，而在session模块中配置文件中端口号也是10000,不知道是不是有问题？
![image](https://user-images.githubusercontent.com/21975431/58559550-f1149600-8255-11e9-9ddc-1b21b6e802ee.png)

**Comment by wubenqi** [comment]
检查10000端口被哪个程序占了，好像迅雷会用

80sAzhong <notifications@github.com> 于 2019年5月29日 周三 21:08写道：

**Comment by 80sAzhong** [comment]
非常感谢您的回复！
      当时检查到的是session模块启动后的服务占用了，正如我前面提出的疑惑，为什么session模块的服务端口也是10000？之前邮件中有截图，源码中定义了这个端口号，在session模块和fronted模块。

发自我的 iPhone

**Comment by 80sAzhong** [comment]
![image](https://user-images.githubusercontent.com/21975431/58600739-5dc07c80-82b8-11e9-9b7b-6f7295244a8d.png)

**Comment by 80sAzhong** [comment]
后面发现该问题不是端口号被占用的问题，而是子节点连接etcd失败，提示终端节点已经存在，问题出在etcd上，同样的问题在ETCD上有人提过，详见https://github.com/etcd-io/etcd/issues/10188
