### ISSUE TITLE
运行frontend时报Endpoint already exists for id

### ISSUE THREAD

**Issue by 80sAzhong** [nebula-chat/chatengine#13]
在完全按照部署启动顺序操作最后一步启动frontend时后台报错退出，提示： Endpoint already exists for id: client-bugdyydaq7ag，请帮忙看一下，谢谢！
![image](https://user-images.githubusercontent.com/21975431/58607173-198da600-82d1-11e9-9cbf-c9fb1bccf70f.png)

**Comment by 80sAzhong** [comment]
后面发现该问题不是端口号被占用的问题，而是子节点连接etcd失败，提示终端节点已经存在，问题出在etcd上，同样的问题在ETCD上有人提过，详见etcd-io/etcd#10188

**Comment by 80sAzhong** [comment]
上面那个问题是由于etcd clientv3上的一个bug引起的详见：https://github.com/etcd-io/etcd/pull/10207/commits/6a43db1effcbe0f1092ad24bfec56c452f58e7ef，建议作者更新一下依赖的etcd版本(v3.4已经修复了该问题)
![image](https://user-images.githubusercontent.com/21975431/58615511-d7bf2880-82ed-11e9-914b-3cbf591d0bed.png)

**Comment by wubenqi** [comment]
好的
