### ISSUE TITLE
go build

### ISSUE THREAD

**Issue by askucher** [nebula-chat/chatengine#15]
I follow this https://github.com/nebula-chat/chatengine

```sh
cd $GOPATH/src/github.com/nebula-chat/chatengine/access/frontend
go build
```
got 

```
root@indachat:/var/workspace/src/github.com/nebula-chat/chatengine/access/frontend# go build
../../vendor/github.com/coreos/etcd/clientv3/auth.go:18:2: cannot find package "context" in any of:
        /var/workspace/src/github.com/nebula-chat/chatengine/vendor/github.com/coreos/etcd/vendor/context (vendor tree)
        /var/workspace/src/github.com/nebula-chat/chatengine/vendor/context
        /usr/lib/go-1.6/src/context (from $GOROOT)
        /var/workspace/src/context (from $GOPATH)
```

Could you help please to build the solution?

**Comment by askucher** [comment]
AH. I found the issue. I use  go1.6.2 linux/amd64. context became a standard library in 1.7

What version of go do you recommend?

**Comment by askucher** [comment]
go version go1.7.1 linux/amd64
root@indachat:/var/workspace# cd src/github.com/nebula-chat/chatengine/access/frontend/
root@indachat:/var/workspace/src/github.com/nebula-chat/chatengine/access/frontend# go build
# github.com/nebula-chat/chatengine/vendor/github.com/coreos/etcd/vendor/go.uber.org/zap
../../vendor/github.com/coreos/etcd/vendor/go.uber.org/zap/field.go:33: syntax error: unexpected = in type declaration

**Comment by askucher** [comment]
installed 
go version go1.9.4 linux/amd64

got 

```
# github.com/nebula-chat/chatengine/vendor/github.com/gomodule/redigo/internal
flag provided but not defined: -goversion
usage: compile [options] file.go...
  -%    debug non-static initializers
```

**Comment by wubenqi** [comment]
go version
go version go1.11.5 linux/amd64

**Comment by askucher** [comment]
thx
