### ISSUE TITLE
How grpc server work with TLSchema client.

### ISSUE THREAD

**Issue by zeinali0** [nebula-chat/chatengine#28]
You used grpc and protobuff in server codes but for client you used the official telegram source codes which is using TLSchema serialization I wonder how this two can work together?
Can you help me?

**Comment by wubenqi** [comment]
Read source code: https://github.com/nebula-chat/chatengine/blob/master/mtproto/codec_schema.tl.pb.go

**Comment by zeinali0** [comment]
So you mean you customized grpc encoding/decoding?
