### ISSUE TITLE
 load and delete session manager

### ISSUE THREAD

**Issue by YumcoderCom** [nebula-chat/chatengine#4]
https://github.com/nebula-chat/chatengine/blob/97ed283fe69c04eb3e3d88de7c1f095296a5131b/access/session/server/server.go#L331

what if at this moment the client creates a new request!

suppose  the client run the following line (line 249) and got ok
```
	if vv, ok := s.sessionManager.Load(authKeyId); !ok {
```
at this moment session handler thread actived and call onCloseSessionClientManager 
dose it need synchronization mechanism?

**Comment by wubenqi** [comment]
right, it need synchronization mechanism.
