### ISSUE TITLE
我想新增个接口，我应该怎么做

### ISSUE THREAD

**Issue by 1920853199** [nebula-chat/chatengine#48]
服务端 mtproto 协议代码生成器可以开放吗，我想新增个接口，我应该怎么做

**Comment by wubenqi** [comment]
请确认是否已经获得授权，如果已经获得授权，请直接和作者联系，如果未获得授权，请主动删除您的版本以避免必要的麻烦。

**Comment by 1920853199** [comment]
已经授权了，我在TG上经常找你的，但是我TG被封了，没办法找你

**Comment by 1920853199** [comment]
已经授权了，我在TG上经常找你的，但是我TG被封了，没办法找你




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "benqi"<notifications@github.com&gt;; 
发送时间: 2020年9月16日(星期三) 上午7:12
收件人: "nebula-chat/chatengine"<chatengine@noreply.github.com&gt;; 
抄送: "LeeChan"<1920853199@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [nebula-chat/chatengine] 我想新增个接口，我应该怎么做 (#48)





 
请确认是否已经获得授权，如果已经获得授权，请直接和作者联系，如果未获得授权，请主动删除您的版本以避免必要的麻烦。

**Comment by 1920853199** [comment]
已经授权的，怎么联系您呢
