### ISSUE TITLE
conversion

### ISSUE THREAD

**Issue by YumcoderCom** [nebula-chat/chatengine#5]
https://github.com/nebula-chat/chatengine/blob/616a06af62755ec67bfaf65789205b5532d5d74b/service/auth_session/biz/core/cache_salt_manager.go#L159

cache adapter is redis, so this datatype conversion always false

error:```interface {} is []uint8, not []*mtproto.FutureSalt_Data```

**Comment by wubenqi** [comment]
thanks, I'll fix it.
